services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "9999:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - central-auth
      - web-app-1
      - web-app-2
    networks:
      - sso-network

  central-auth:
    build: ./central-auth
    container_name: central-auth-service
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - sso-network

  database:
    image: postgres:15-alpine
    container_name: sso-postgres
    environment:
      POSTGRES_DB: sso_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sso-network

  web-app-1:
    build: ./web-app-1
    container_name: app1-service
    ports:
      - "5000:5000"
    networks:
      - sso-network

  web-app-2:
    build: ./web-app-2
    container_name: app2-service
    ports:
      - "5001:5001"
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge