# Localhost / Docker internal bridge network
client dockernet {
    ipaddr = 0.0.0.0/0
    secret = sso_secret_123
    require_message_authenticator = no
    nastype = other
}

# Local loopback client for radtest testing
client localhost {
    ipaddr = 127.0.0.1
    secret = sso_secret_123
    require_message_authenticator = no
    nastype = other
}