prefix = /usr
sysconfdir = /etc
raddbdir = ${sysconfdir}/raddb


log {
    destination = stdout
}

security {
    max_request_time = 30
}

modules {
    pap {
    }
    files {
        filename = ${raddbdir}/users
    }
    
    # Uncomment the line below to load the LDAP module
    # $INCLUDE ldap.conf
}

server default {
    listen {
        type = auth
        ipaddr = *
        port = 1812
    }
    listen {
        type = acct
        ipaddr = *
        port = 1813
    }

    authorize {
        files
        
        # Uncomment the line below to check LDAP for users
        # ldap
        
        pap
    }

    authenticate {
        pap
        
        # Uncomment the block below to verify passwords against LDAP
        # Auth-Type LDAP {
        #     ldap
        # }
    }

    post-auth {
        Post-Auth-Type Reject {
            update reply {
                Reply-Message := "Authentication failed"
            }
        }
    }
}

$INCLUDE clients.conf